POST http://localhost:6969/api/rating
Content-Type: application/json

{
  "userId": "222222222222",
  "movieId": "2121",
  "rating": 3
}
###

GET http://localhost:6969/api/rating/
Content-Type: application/json

###

GET http://localhost:6969/api/rating/
Content-Type: application/json

###

PUT http://localhost:6969/api/rating/66681893d9ff098b490e3b09
Content-Type: application/json

{
 "rating": 0
}