export * from "./MainPage/MainPage";
export * from "./AuthPage/AuthPage";
export * from "./Root/Root";
export * from "./NotFound/NotFound";
export * from "./Friends/Friends";
export * from "./Movies/Movies";
export * from "./NewsFeed/NewsFeed";
export * from "./MyList/MyList";
export * from "./Profile/Profile";